/* DO NOT EDIT THIS FILE - it is machine generated */
/* Ooops - I edited it (to remove QtApplication stuff which is described in
   existing headers. */
#include <jni.h>
/* Header for class com_nokia_qt_QtApplication */

#ifndef _Included_com_nokia_qt_android_QtApplication
#define _Included_com_nokia_qt_android_QtApplication
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nokia_qt_android_QtApplication_moveThreshold
#define com_nokia_qt_android_QtApplication_moveThreshold 0L

/*
 * Class:     com_nokia_qt_android_QtApplication
 * Method:    g_position_updated
 * Signature: (DDDDD)V
 */
JNIEXPORT void JNICALL Java_com_nokia_qt_android_QtApplication_g_1position_1updated
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
