TEMPLATE = subdirs
SUBDIRS = ch gg osmr mr utt qr mf
ch.file = contractionhierarchies/contractionhierarchiesclient.pro
gg.file = gpsgrid/gpsgridclient.pro
osmr.file = osmrenderer/osmrendererclient.pro
mr.file = osmrenderer/mapnikrendererclient.pro
qr.file = osmrenderer/qtilerendererclient.pro
mf.file = osmrenderer/mapsforgerendererclient.pro
utt.file = unicodetournamenttrie/unicodetournamenttrieclient.pro
