TEMPLATE = subdirs
SUBDIRS = ch gg osmr mr qr utt osmi ti
ch.file = contractionhierarchies/contractionhierarchies.pro
gg.file = gpsgrid/gpsgrid.pro
osmr.file = osmrenderer/osmrenderer.pro
mr.file = osmrenderer/mapnikrenderer.pro
qr.file = osmrenderer/qtilerenderer.pro
utt.file = unicodetournamenttrie/unicodetournamenttrie.pro
osmi.file = osmimporter/osmimporter.pro
ti.file = testimporter/testimporter.pro
